name: build-and-deploy-poc-barcode-scanning
run-name: Build and deploy of the poc barcode scanning application as github page
on: [push]
jobs:
  build-poc-barcode-scanning:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm ci
      - name: build the angular application
        run: npx ng build --base-href=/poc-barcode-scanning/
      - name: archive the build application
        uses: actions/upload-artifact@v4
        with:
          path: dist/poc-barcode-scanning/browser
  deploy-poc-barcode-scanning:
    needs: build-poc-barcode-scanning
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4
